# Generated by Django 4.1 on 2022-09-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogger',
            old_name='profesion_id',
            new_name='profesion',
        ),
    ]
