# Generated by Django 4.1 on 2022-09-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_rename_profesion_id_blogger_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(default='Articulo Python', max_length=250),
        ),
    ]
