# Generated by Django 4.1 on 2022-09-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_rename_nombre_articulo_subtitulo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogger',
        ),
        migrations.DeleteModel(
            name='Profesion',
        ),
    ]
